name: Build docker image
on:
  push:
    branches: ['develop', 'main']
    tags:
    - v*.*.*

jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: ${{ github.repository }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup golang
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
        cache: true
    - name: Generate ABI
      run: |
        go install github.com/ethereum/go-ethereum/cmd/abigen@latest
        mv $(go env GOPATH)/bin/abigen /usr/local/bin
        make abigen
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v2
    - name: Login in to Github registry
      uses: docker/login-action@v2
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/${{ env.IMAGE_NAME }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: '.'
        push: ${{ github.event_name != 'pull_request' }}
        file: ./Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
